In [2]:
import pandas as pd

In [4]:
df=pd.read_csv('task.csv')

In [5]:
df

     NAME  MATH  SCIENCE  HINDI  COMPUTER
0   sneha    25       72     29        45
1    aman    36       65     35        79
2  saloni    50       49     51        53
3   aditi    44       85     65        65
4   sonam    62       26     25        58
5  antima    95       43     84        39
6  shakti    78       54     79        49
7    ruby    63       36     85        63
8   mohit    41       66     45        52
9    abhi    85       33     46        97

In [25]:
data={"name":['sneha','aman','antima','mohit','ruby'],
      "science":[50,60,25,38,42],
       "hindi":[40,20,55,63,42],
       "computer":[20,40,85,61,36],
       "math":[87,54,95,65,25]
}

In [26]:
df=pd.DataFrame(data)

In [27]:
df["math"].mean()

np.float64(65.2)

In [28]:
df["computer"].max()

np.int64(85)

In [39]:
df["total"]=df["math"]+df["computer"]+df["hindi"]+df["science"]

In [40]:
df

     name  science  hindi  computer  math  total
0   sneha       50     40        20    87    197
1    aman       60     20        40    54    174
2  antima       25     55        85    95    260
3   mohit       38     63        61    65    227
4    ruby       42     42        36    25    145

In [49]:
[df[df["total"]==df["total"].max()]]

[     name  science  hindi  computer  math  total
 2  antima       25     55        85    95    260]